import 'package:first_project/view/page/bar_list_page.dart';
import 'package:first_project/view/page/category_restaurant_page.dart';
import 'package:first_project/view/page/chinese_list_page.dart';
import 'package:first_project/view/page/coffee_list_page.dart';
import 'package:first_project/view/page/dessert_list_page.dart';
import 'package:first_project/view/page/detail_restaurant_page.dart';
import 'package:first_project/view/page/find_restaurant_page.dart';
import 'package:first_project/view/page/find_station_page.dart';
import 'package:first_project/view/page/fusion_list_page.dart';
import 'package:first_project/view/page/japanese_list_page.dart';
import 'package:first_project/view/page/korean_list_page.dart';
import 'package:first_project/view/page/find_password_page.dart';
import 'package:first_project/view/page/login_page.dart';
import 'package:first_project/view/page/main_page.dart';
import 'package:first_project/view/page/map_page.dart';
import 'package:first_project/view/page/membership_withdrawal_page.dart';
import 'package:first_project/view/page/my_review_page.dart';
import 'package:first_project/view/page/review_detail_page.dart';
import 'package:first_project/view/page/review_page.dart';
import 'package:first_project/view/page/signup_page.dart';
import 'package:first_project/view/page/western_list_page.dart';
import 'package:first_project/view/page/world_list_page.dart';
import 'package:first_project/view/screen/like_screen.dart';
import 'package:first_project/view/screen/main_screen.dart';
import 'package:first_project/view/screen/my_screen.dart';
import 'package:first_project/view/screen/search_screen.dart';

class AppRoutes {
  static const login = LoginPage.route;
  static const findPassword = FindPasswordPage.route;
  static const signup = SignupPage.route;
  static const mainScreen = MainScreen.route;
  static const korean = KoreanListPage.route;
  static const main = MainPage.route;
  static const searchScreen = SearchScreen.route;
  static const likeScreen = LikeScreen.route;
  static const myScreen = MyScreen.route;
  // static const findRestaurant = FindRestaurantPage.route;
  static const detailRestaurant = DetailRestaurantPage.route;
  static const mapPage = MapPage.route;
  static const findStation = FindStationPage.route;
  static const chinese = ChineseListPage.route;
  static const japanese = JapaneseListPage.route;
  static const western = WesternListPage.route;
  static const dessert = DessertListPage.route;
  static const bar = BarListPage.route;
  static const world = WorldListPage.route;
  static const fusion = FusionListPage.route;
  static const coffee = CoffeeListPage.route;
  static const myReview = MyReviewPage.route;
  static const membershipWithdrawal = MembershipWithdrawalPage.route;
  static const category = CategoryRestaurantPage.route;
  static const review = ReviewPage.route;
  static const reviewDetail = ReviewDetailPage.route;
}
